version: "2"
services:
  chat-ms:
    build: .
    ports:
      - "3001:3000"
    labels:
      io.rancher.scheduler.affinity:host_label: "id=n3"
    depends_on:
      - chat-db
  chat-db:
    image: mongo
    ports:
      - "3306:27017"
    labels:
      io.rancher.scheduler.affinity:host_label: "id=n3"
